server:
  port: 8080
  servlet:
    context-path: /s001
    session:
      timeout: 120m
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 600
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/interview_db_001?characterEncoding=utf-8&serverTimezone=GMT%2B8
    hikari:
      minimum-idle: 2
      pool-name: s001-hikaripool
      connection-timeout: 30000
      maximum-pool-size: 200
  profiles:
    include: config
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
     mapper: debug